language: python
python:
  - "3.4"
cache: pip
# command to install dependencies
branches:
  only:
  - source
install:
- pip install --upgrade pip
- pip install --upgrade wheel
- pip install --upgrade setuptools
- pip install -r requirements.txt
before_script:
- pelican-themes -i ./theme/elegant
script:
- make publish github
env:
  global:
  - secure: GH_KEY
