language: python
python:
  - "3.4"
cache: pip
# command to install dependencies
branches:
  only:
  - master
install:
- pip install --upgrade pip
- pip install --upgrade wheel
- pip install --upgrade setuptools
- pip install pelican ghp-import
before_script:
#- pelican-themes -i ./theme
script:
- make publish github
