language: python
python:
  - "3.4"
cache: pip
# command to install dependencies
branches:
  only:
  - master
install:
- pip install --upgrade pip
- pip install --upgrade wheel
- pip install --upgrade setuptools
- pip install pelican ghp-import Markdown typogrify ghp-import
before_script:
#- pelican-themes -i ./theme
script:
- echo "Starting my commands..."
- pwd
- whoami
- ls
- echo 'files in content/content'
- ls content/content
- make publish github
